sonata_admin:
    title: 'Agence'
    title_logo: images\house.png

    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    options:
        # ...
          mosaic_background: '/images/house.png'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
