# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
        locale: 'en'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    admin.property_Admin:
            class: App\Admin\PropertyAdmin
            arguments: [~, App\Entity\Property, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Property }




    admin.choix_Admin:
            class: App\Admin\ChoixAdmin
            arguments: [~, App\Entity\Choix, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Choix }

    admin.Equipement_Admin:
            class: App\Admin\EquipementAdmin
            arguments: [~, App\Entity\Equip, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Equipement }

    admin.Heat_Admin:
            class: App\Admin\HeatAdmin
            arguments: [~, App\Entity\Heat, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Heat }

    admin.Room_Admin:
            class: App\Admin\RoomsAdmin
            arguments: [~, App\Entity\Room, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Rooms }